version: '3.3'

services:
  bhb_database:
    container_name: bhb_database
    image: postgres:11.2-alpine
    restart: always
    ports:
      - '4444:4444'
    environment:
      POSTGRES_DB: blog_bholder
      POSTGRES_PASSWORD: '123456'
      PGPORT: 4444
